import * as vscode from 'vscode';
import * as path from 'path';
import * as cp from 'child_process';
import * as fs from 'fs';
import { SearchableItem, SearchItemType } from './core/types';
import { Config } from './config';
import { IndexPersistence } from './core/index-persistence';

/**
 * Workspace indexer that scans files and extracts symbols
 */
export class WorkspaceIndexer {
    private items: SearchableItem[] = [];
    private indexing: boolean = false;
    private config: Config;
    private fileWatcher: vscode.FileSystemWatcher | undefined;
    private treeSitter: import('./core/tree-sitter-parser').TreeSitterParser;
    private persistence: IndexPersistence;
    private fileHashes: Map<string, string> = new Map();

    constructor(config: Config, treeSitter: import('./core/tree-sitter-parser').TreeSitterParser, persistence: IndexPersistence) {
        this.config = config;
        this.treeSitter = treeSitter;
        this.persistence = persistence;
    }

    /**
   * Start indexing the workspace
   */
    async indexWorkspace(
        progressCallback?: (message: string, increment?: number) => void
    ): Promise<void> {
        if (this.indexing) {
            return;
        }

        this.indexing = true;
        this.items = [];

        try {
            const workspaceFolders = vscode.workspace.workspaceFolders;
            if (!workspaceFolders) {
                return;
            }

            // Load cache
            await this.persistence.load();

            // Try to get git hashes
            await this.populateFileHashes();

            // Index files
            progressCallback?.('Scanning workspace files...', 0);
            await this.indexFiles();

            // Index symbols from files
            await this.indexSymbols(progressCallback);

            // Save cache
            await this.persistence.save();

            // Set up file watchers for incremental updates
            this.setupFileWatchers();
        } finally {
            this.indexing = false;
        }
    }

    /**
     * Get all indexed items
     */
    getItems(): SearchableItem[] {
        return this.items;
    }

    /**
     * Check if indexing is in progress
     */
    isIndexing(): boolean {
        return this.indexing;
    }

    /**
     * Index all files in workspace
     */
    private async indexFiles(): Promise<void> {
        const excludePatterns = this.config.getExcludePatterns();
        const fileExtensions = this.config.getFileExtensions();
        const respectGitignore = this.config.shouldRespectGitignore();

        // Build glob patterns
        const includePattern = `**/*.{${fileExtensions.join(',')}}`;

        // VS Code's findFiles automatically respects:
        // 1. files.exclude setting
        // 2. .gitignore files (if respectGitignore is true, which is default)
        // 3. Our custom exclude patterns
        const excludePattern = `{${excludePatterns.join(',')}}`;

        // Note: VS Code respects .gitignore files by default when using workspace.findFiles
        // The search.useIgnoreFiles setting controls this (defaults to true)
        const files = await vscode.workspace.findFiles(includePattern, excludePattern);

        for (const file of files) {
            // Skip C# auto-generated files
            if (file.fsPath.endsWith('.cs')) {
                const isAutoGenerated = await this.isAutoGeneratedFile(file);
                if (isAutoGenerated) {
                    continue; // Skip this file
                }
            }

            const fileName = path.basename(file.fsPath);
            const relativePath = vscode.workspace.asRelativePath(file.fsPath);

            this.items.push({
                id: `file:${file.fsPath}`,
                name: fileName,
                type: SearchItemType.FILE,
                filePath: file.fsPath,
                detail: relativePath,
                fullName: relativePath,
            });
        }
    }

    /**
     * Check if a file is auto-generated (C# files with // <auto-generated /> marker)
     * Optimized to avoid opening a full VS Code document
     */
    private async isAutoGeneratedFile(fileUri: vscode.Uri): Promise<boolean> {
        try {
            // Read only first 1KB to check for marker - much faster than openTextDocument
            const buffer = await vscode.workspace.fs.readFile(fileUri);
            const content = Buffer.from(buffer.slice(0, 1024)).toString('utf8');

            if (!content) return false;

            const firstLine = content.split('\n')[0].trim();

            // Check for common auto-generated markers in C#
            return (
                firstLine === '// <auto-generated />' ||
                firstLine === '// <auto-generated/>' ||
                firstLine.startsWith('// <auto-generated>') ||
                content.includes('<auto-generated') // Some files have it later or in a header block
            );
        } catch (error) {
            return false;
        }
    }

    /**
     * Index symbols from all files with optimized concurrency (Sliding Window)
     */
    private async indexSymbols(
        progressCallback?: (message: string, increment?: number) => void
    ): Promise<void> {
        const fileItems = this.items.filter((item) => item.type === SearchItemType.FILE);
        const totalFiles = fileItems.length;

        if (totalFiles === 0) return;

        // HIGH-PERFORMANCE PASS 1: Try workspace-wide symbol extraction (often covers 80% of symbols in 1 call)
        progressCallback?.('Fast-scanning workspace symbols...', 5);
        try {
            const workspaceSymbols = await vscode.commands.executeCommand<vscode.SymbolInformation[]>(
                'vscode.executeWorkspaceSymbolProvider',
                ''
            );

            if (workspaceSymbols && workspaceSymbols.length > 0) {
                this.processWorkspaceSymbols(workspaceSymbols);
            }
        } catch (e) {
            console.log('Workspace symbol pass failed, moving to file-by-file...');
        }

        // HIGH-PERFORMANCE PASS 2: Sliding Window Concurrent Pool
        const CONCURRENCY = 50;
        let processed = 0;
        let activeWorkers = 0;
        let currentIndex = 0;

        return new Promise((resolve) => {
            const startNextWorker = async () => {
                if (currentIndex >= totalFiles) {
                    if (activeWorkers === 0) resolve();
                    return;
                }

                const fileItem = fileItems[currentIndex++];
                activeWorkers++;

                try {
                    await this.indexFileSymbols(vscode.Uri.file(fileItem.filePath));
                } catch (error) {
                    // Fail silently
                }

                processed++;
                activeWorkers--;

                if (processed % 20 === 0 || processed === totalFiles) {
                    const fileName = path.basename(fileItem.filePath);
                    progressCallback?.(
                        `Indexing ${fileName} (${processed}/${totalFiles})`,
                        (20 / totalFiles) * 70
                    );
                }

                startNextWorker();
            };

            for (let i = 0; i < Math.min(CONCURRENCY, totalFiles); i++) {
                startNextWorker();
            }
        });
    }

    /**
     * Process symbols from workspace provider
     */
    private processWorkspaceSymbols(symbols: vscode.SymbolInformation[]): void {
        for (const symbol of symbols) {
            const itemType = this.mapSymbolKindToItemType(symbol.kind);
            if (!itemType) continue;

            const id = `symbol:${symbol.location.uri.fsPath}:${symbol.name}:${symbol.location.range.start.line}`;
            if (this.items.some(i => i.id === id)) continue;

            this.items.push({
                id,
                name: symbol.name,
                type: itemType,
                filePath: symbol.location.uri.fsPath,
                line: symbol.location.range.start.line,
                column: symbol.location.range.start.character,
                containerName: symbol.containerName,
                fullName: symbol.containerName ? `${symbol.containerName}.${symbol.name}` : symbol.name,
            });
        }
    }

    /**
   * Index symbols from a single file with caching
   */
    private async indexFileSymbols(fileUri: vscode.Uri): Promise<void> {
        const filePath = fileUri.fsPath;
        const stats = await vscode.workspace.fs.stat(fileUri);
        const mtime = stats.mtime;
        const currentHash = this.fileHashes.get(filePath);

        // Check cache
        const cached = this.persistence.get(filePath);
        if (cached && (currentHash ? cached.hash === currentHash : cached.mtime === mtime)) {
            this.items.push(...cached.symbols);
            return;
        }

        try {
            let symbolsFound: SearchableItem[] = [];

            // TURBO PATH: Try Tree-sitter first
            const treeSitterItems = await this.treeSitter.parseFile(fileUri);
            if (treeSitterItems.length > 0) {
                symbolsFound = treeSitterItems;
            } else {
                // FALLBACK PATH: Use VS Code's DocumentSymbolProvider
                const symbols = await vscode.commands.executeCommand<vscode.DocumentSymbol[]>(
                    'vscode.executeDocumentSymbolProvider',
                    fileUri
                );

                if (symbols && symbols.length > 0) {
                    // Temporarily store in current items to process
                    const startIndex = this.items.length;
                    this.processSymbols(symbols, filePath);
                    symbolsFound = this.items.slice(startIndex).filter(i => i.type !== SearchItemType.FILE);

                    // Since we added to this.items in processSymbols, but we want to return results for caching
                    // We'll leave them in this.items but also save them to cache below
                } else {
                    // Try one more time by opening document if empty
                    const document = await vscode.workspace.openTextDocument(fileUri);
                    await new Promise(resolve => setTimeout(resolve, 200));
                    const retrySymbols = await vscode.commands.executeCommand<vscode.DocumentSymbol[]>(
                        'vscode.executeDocumentSymbolProvider',
                        fileUri
                    );

                    if (retrySymbols && retrySymbols.length > 0) {
                        const startIndex = this.items.length;
                        this.processSymbols(retrySymbols, filePath);
                        symbolsFound = this.items.slice(startIndex).filter(i => i.type !== SearchItemType.FILE);
                    }
                }
            }

            // Update cache and push (if not already pushed by fallback loop)
            if (symbolsFound.length > 0) {
                this.persistence.set(filePath, {
                    mtime,
                    hash: currentHash,
                    symbols: symbolsFound
                });

                // If the symbols were found via tree-sitter, we need to add them to this.items
                // If they were found via falling back to processSymbols, they are already in this.items
                const alreadyInItems = this.items.some(i => i.filePath === filePath && i.type !== SearchItemType.FILE);
                if (!alreadyInItems) {
                    this.items.push(...symbolsFound);
                }
            }
        } catch (error) {
            console.log(`Could not extract symbols from ${filePath}: ${error}`);
        }
    }

    /**
     * Get git hashes for files (Fast Cache Key)
     */
    private async populateFileHashes(): Promise<void> {
        this.fileHashes.clear();
        const workspaceFolders = vscode.workspace.workspaceFolders;
        if (!workspaceFolders) return;

        for (const folder of workspaceFolders) {
            try {
                const output = cp.execSync('git ls-files --stage', {
                    cwd: folder.uri.fsPath,
                    maxBuffer: 10 * 1024 * 1024 // 10MB buffer for large repos
                }).toString();

                const lines = output.split('\n');
                for (const line of lines) {
                    const match = line.match(/^\d+\s+([a-f0-9]+)\s+\d+\s+(.+)$/);
                    if (match) {
                        const hash = match[1];
                        const relPath = match[2];
                        const fullPath = path.join(folder.uri.fsPath, relPath);
                        this.fileHashes.set(fullPath, hash);
                    }
                }
            } catch (e) {
                // Git failed or not a repo, skip hashing
            }
        }
    }

    /**
     * Process symbols recursively
     */
    private processSymbols(
        symbols: vscode.DocumentSymbol[],
        filePath: string,
        containerName?: string
    ): void {
        for (const symbol of symbols) {
            const itemType = this.mapSymbolKindToItemType(symbol.kind);
            if (itemType) {
                const fullName = containerName ? `${containerName}.${symbol.name}` : symbol.name;

                this.items.push({
                    id: `symbol:${filePath}:${fullName}:${symbol.range.start.line}`,
                    name: symbol.name,
                    type: itemType,
                    filePath,
                    line: symbol.range.start.line,
                    column: symbol.range.start.character,
                    containerName,
                    fullName,
                    detail: symbol.detail,
                });
            }

            // Process nested symbols
            if (symbol.children && symbol.children.length > 0) {
                const newContainerName = containerName ? `${containerName}.${symbol.name}` : symbol.name;
                this.processSymbols(symbol.children, filePath, newContainerName);
            }
        }
    }

    /**
     * Map VS Code SymbolKind to our SearchItemType
     */
    private mapSymbolKindToItemType(kind: vscode.SymbolKind): SearchItemType | null {
        switch (kind) {
            case vscode.SymbolKind.Class:
                return SearchItemType.CLASS;
            case vscode.SymbolKind.Interface:
                return SearchItemType.INTERFACE;
            case vscode.SymbolKind.Enum:
                return SearchItemType.ENUM;
            case vscode.SymbolKind.Function:
                return SearchItemType.FUNCTION;
            case vscode.SymbolKind.Method:
                return SearchItemType.METHOD;
            case vscode.SymbolKind.Property:
            case vscode.SymbolKind.Field:
                return SearchItemType.PROPERTY;
            case vscode.SymbolKind.Variable:
            case vscode.SymbolKind.Constant:
                return SearchItemType.VARIABLE;
            default:
                return null; // Skip other symbol kinds
        }
    }

    /**
     * Setup file watchers for incremental updates
     */
    private setupFileWatchers(): void {
        const fileExtensions = this.config.getFileExtensions();
        const pattern = `**/*.{${fileExtensions.join(',')}}`;

        this.fileWatcher = vscode.workspace.createFileSystemWatcher(pattern);

        // Handle file creation
        this.fileWatcher.onDidCreate((uri) => {
            this.handleFileCreated(uri);
        });

        // Handle file changes
        this.fileWatcher.onDidChange((uri) => {
            this.handleFileChanged(uri);
        });

        // Handle file deletion
        this.fileWatcher.onDidDelete((uri) => {
            this.handleFileDeleted(uri);
        });
    }

    /**
     * Handle file created
     */
    private async handleFileCreated(uri: vscode.Uri): Promise<void> {
        const fileName = path.basename(uri.fsPath);
        const relativePath = vscode.workspace.asRelativePath(uri.fsPath);

        // Add file item
        this.items.push({
            id: `file:${uri.fsPath}`,
            name: fileName,
            type: SearchItemType.FILE,
            filePath: uri.fsPath,
            detail: relativePath,
            fullName: relativePath,
        });

        // Index symbols
        await this.indexFileSymbols(uri);
    }

    /**
     * Handle file changed
     */
    private async handleFileChanged(uri: vscode.Uri): Promise<void> {
        // Remove old symbols for this file
        this.items = this.items.filter(
            (item) => item.filePath !== uri.fsPath || item.type === SearchItemType.FILE
        );

        // Re-index symbols
        await this.indexFileSymbols(uri);
    }

    /**
     * Handle file deleted
     */
    private handleFileDeleted(uri: vscode.Uri): void {
        // Remove all items for this file
        this.items = this.items.filter((item) => item.filePath !== uri.fsPath);
    }

    /**
     * Dispose resources
     */
    dispose(): void {
        this.fileWatcher?.dispose();
    }
}
